// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: payment.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlipayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Goods         []*Goods               `protobuf:"bytes,2,rep,name=goods,proto3" json:"goods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlipayRequest) Reset() {
	*x = AlipayRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlipayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlipayRequest) ProtoMessage() {}

func (x *AlipayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlipayRequest.ProtoReflect.Descriptor instead.
func (*AlipayRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *AlipayRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AlipayRequest) GetGoods() []*Goods {
	if x != nil {
		return x.Goods
	}
	return nil
}

type AlipayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	Total         float32                `protobuf:"fixed32,3,opt,name=total,proto3" json:"total,omitempty"`
	PayUrl        string                 `protobuf:"bytes,5,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlipayResponse) Reset() {
	*x = AlipayResponse{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlipayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlipayResponse) ProtoMessage() {}

func (x *AlipayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlipayResponse.ProtoReflect.Descriptor instead.
func (*AlipayResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *AlipayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AlipayResponse) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *AlipayResponse) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AlipayResponse) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

type Goods struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsID       int64                  `protobuf:"varint,1,opt,name=goodsID,proto3" json:"goodsID,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goods) Reset() {
	*x = Goods{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goods) ProtoMessage() {}

func (x *Goods) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goods.ProtoReflect.Descriptor instead.
func (*Goods) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *Goods) GetGoodsID() int64 {
	if x != nil {
		return x.GoodsID
	}
	return 0
}

func (x *Goods) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type PaymentNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentNotifyRequest) Reset() {
	*x = PaymentNotifyRequest{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentNotifyRequest) ProtoMessage() {}

func (x *PaymentNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentNotifyRequest.ProtoReflect.Descriptor instead.
func (*PaymentNotifyRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentNotifyRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type PaymentNotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentNotifyResponse) Reset() {
	*x = PaymentNotifyResponse{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentNotifyResponse) ProtoMessage() {}

func (x *PaymentNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentNotifyResponse.ProtoReflect.Descriptor instead.
func (*PaymentNotifyResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentNotifyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PaymentNotifyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\"N\n" +
	"\rAlipayRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12$\n" +
	"\x05goods\x18\x02 \x03(\v2\x0e.payment.GoodsR\x05goods\"s\n" +
	"\x0eAlipayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\aorderSn\x18\x02 \x01(\tR\aorderSn\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x02R\x05total\x12\x17\n" +
	"\apay_url\x18\x05 \x01(\tR\x06payUrl\"=\n" +
	"\x05Goods\x12\x18\n" +
	"\agoodsID\x18\x01 \x01(\x03R\agoodsID\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"1\n" +
	"\x14PaymentNotifyRequest\x12\x19\n" +
	"\border_sn\x18\x01 \x01(\tR\aorderSn\"K\n" +
	"\x15PaymentNotifyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa1\x01\n" +
	"\x0ePaymentService\x129\n" +
	"\x06Alipay\x12\x16.payment.AlipayRequest\x1a\x17.payment.AlipayResponse\x12T\n" +
	"\x13HandlePaymentNotify\x12\x1d.payment.PaymentNotifyRequest\x1a\x1e.payment.PaymentNotifyResponseB\x03Z\x01.b\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_payment_proto_goTypes = []any{
	(*AlipayRequest)(nil),         // 0: payment.AlipayRequest
	(*AlipayResponse)(nil),        // 1: payment.AlipayResponse
	(*Goods)(nil),                 // 2: payment.Goods
	(*PaymentNotifyRequest)(nil),  // 3: payment.PaymentNotifyRequest
	(*PaymentNotifyResponse)(nil), // 4: payment.PaymentNotifyResponse
}
var file_payment_proto_depIdxs = []int32{
	2, // 0: payment.AlipayRequest.goods:type_name -> payment.Goods
	0, // 1: payment.PaymentService.Alipay:input_type -> payment.AlipayRequest
	3, // 2: payment.PaymentService.HandlePaymentNotify:input_type -> payment.PaymentNotifyRequest
	1, // 3: payment.PaymentService.Alipay:output_type -> payment.AlipayResponse
	4, // 4: payment.PaymentService.HandlePaymentNotify:output_type -> payment.PaymentNotifyResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
